name: sBank
version: '1.2.1'
main: com.spearforge.sBank.SBank
api-version: 1.13
depend:
  - Vault
commands:
  sbank:
    description: Main command for the bank plugin.
    usage: /<command>
    aliases:
      - sb
      - bank