name: sBank Maven Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sBank BuildTarget
          path: target/**/* # Garante que qualquer arquivo em target será incluído

  artifact:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: sBank BuildTarget
      
      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: sBank PluginJar
          path: target/*.jar
